imports:
    - { resource: config.yml }
#    - { resource: heroku_database.php }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: debug
            handler:      nested
        nested:
            type:  stream
            path:  "php://stdout"
            level: debug
        console:
            type:  console

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_pgsql
        url: "%database_url%"
        host: ~
        port: ~
        dbname: ~
        user: ~
        password: ~